frontend/src/containers/Recipe/Recipe.jsx

MS-106: Image upload/view styling in edit
MS-106: Upload and receive images
MS-106: Don't show upload button if not editing
> [MatterSpace PBI](https://matterstore.atlassian.net/browse/MS-)

MS-106: Ammending blotched main with squashed commits

---

backend/README.md
backend/models/recipe.ts
backend/routes/recipe.ts
backend/tests/helpers.ts
backend/tests/recipe.test.ts

> [MatterSpace PBI](https://matterstore.atlassian.net/browse/MS-121)
Support for multiple images on the backend
`npm run test`

MS-121: Support multiple images on the backend

---

backend/routes/collection.ts
backend/tests/collection.test.ts
frontend/src/api/routes.js
frontend/src/components/floating-menu/MenuEntry.jsx
frontend/src/containers/Recipe/Recipe.jsx

> [MatterSpace PBI](https://matterstore.atlassian.net/browse/MS-107)

MS-107: display all collections on edit and be able to add to collection

---

frontend/src/containers/Listing/Listing.jsx

- Move filter to its own function for *modularity*
**Release Note:** Moved filter so we can reuse.

Feat: Move filtering to its own function, so we an call it in multiple places

---

backend/app.ts

> [MatterSpace PBI](https://matterstore.atlassian.net/browse/MS-123)

MS-123: Upload limit

---

frontend/src/components/Recipe.jsx

> [MatterSpace PBI](https://matterstore.atlassian.net/browse/MS-124)
Actually show preview thumbnail on listings.
View listings page, ensure preview thumbnails show up.

MS-124: Fall back to first image if prop missing

---

frontend/src/containers/Listing/Listing.jsx

- No longer show empty collections on listing page
**Release Note:** No longer shows empty colletions on listings page.

Fix: Dont show empty collections

---

frontend/src/components/ListTextArea.jsx

> [MatterSpace PBI](https://matterstore.atlassian.net/browse/MS-125)
Fixes an issue where steps are shown as unordered
Check steps appear ordered
Fix how steps are rendered

MS-125: Show numbered list for steps

---

frontend/src/containers/Home/Home.jsx

- Added foodify on splash page
**Release Note:** Added foodify on splash page

feat: Add foodify on splash page

---

.github/workflows/frontend-tests.yml
frontend/.babel.config.js
frontend/src/App.js
frontend/src/App.test.js
frontend/src/components/__tests__/ButtonTest.js
frontend/src/components/floating-menu/__tests__/FloatingMenuParentTest.js
frontend/src/components/floating-menu/__tests__/FloatingMenuTest.js
frontend/src/containers/ChangePassword.jsx
frontend/src/containers/Home.jsx
frontend/src/containers/Listing.jsx
frontend/src/containers/Login.jsx
frontend/src/containers/Recipe.jsx
frontend/src/containers/Signup.jsx
frontend/src/containers/__tests__/HomeTest.js
frontend/src/containers/__tests__/LoginTest.js
frontend/src/containers/__tests__/SignupTest.js
package-lock.json
package.json

> [MatterSpace PBI](https://matterstore.atlassian.net/browse/MS-128)
- Introduces basic front end component and container tests
- Check tests pass and are reasonable
- Add front-end unit tests

MS-128: Front end tests

---

backend/routes/collection.ts
backend/tests/collection.test.ts
frontend/src/api/routes.js
frontend/src/containers/Recipe.jsx

> [MatterSpace PBI](https://matterstore.atlassian.net/browse/MS-126) and [MatterSpace PBI](https://matterstore.atlassian.net/browse/MS-114) and [MatterSpace PBI](https://matterstore.atlassian.net/browse/MS-129)
https://user-images.githubusercontent.com/14151679/200464502-057be1fc-ec1a-4858-b7bf-f09b92db0aa0.mov

Feat/MS-126 collections: create, remove and delete

---

frontend/src/containers/ChangePassword.jsx
frontend/src/containers/Login.jsx
frontend/src/containers/Recipe.jsx
frontend/src/containers/Signup.jsx

- Having to double click submit buttons on forms
Try login, should only take one click now
**Release Note:** Fixed having to double click submit buttons.

Fix: No longer use state for checking wether or not form is valid

---

frontend/src/App.js
frontend/src/api/routes.js
frontend/src/components/Nav.jsx
frontend/src/containers/ChangePassword.jsx
frontend/src/containers/Listing.jsx
frontend/src/containers/Login.jsx
frontend/src/containers/Recipe.jsx

- Adds two seperate listings pages for public and private recipes
- Click on home and my Recipes
**Release Note:** Added ability to browser public and private recipes.

Feat: Cleaned up routes and made public and private listing pages

---

frontend/src/containers/Recipe.jsx

> [MatterSpace PBI](https://matterstore.atlassian.net/browse/MS-130)
Introduced image deletion
Try and delete an image
- Support image deletion from recipes

MS-130: Image deletion

---

frontend/src/api/routes.js
frontend/src/components/Nav.jsx
frontend/src/containers/Recipe.jsx

> [No PBI](https://matterstore.atlassian.net/browse/MS-)
- Hide recipe edit button when user is not the owner
- Update header to show...
- Log in and out and try to edit recieps and check the header
**Release Note:** Fixed showing user actions they couldn't use, base on authentication status.

Feat: Hide recipe edit when not logged in or not users recipe, and update header based on authentication status

---

frontend/src/components/Button.jsx
frontend/src/components/SaveButton.jsx
frontend/src/components/SubmitButton.jsx
frontend/src/containers/Home.jsx

- Continue as guest button
- on hover actions to current buttons
- Press the button
**Release Note:** Added continue as guest button, and on hvoer action.

Feat: Added continue as guest button, and added on:hover actions to our buttons

---

frontend/src/containers/Recipe.jsx

- Removing recipe from its respective collection on delete
**Release Note:** Clean up collection on recipe delete.

Fix: Remove recipes from collection on delete

---

frontend/src/components/DeleteButton.jsx
frontend/src/containers/Listing.jsx

- Allows user s to delete collection they own
- Mkae a new collection, navigate to my Recieps, delete collection
**Release Note:** Added ability to delete collection.

Feat: Added delete button that only shows if user owns collection

---

frontend/src/components/Nav.jsx

**Release Note:** Renamed Home -> Public Recipes.

Chore: Renamed Home to public recipes so we dont have the expectation of our private recipes showing cause I CBF ficing

---

frontend/src/containers/Listing.jsx

- Hiding recipe create button
**Release Note:** Hide recipe create button when user is unathenticated.

Fix: Hid create button behind authentication

---

frontend/src/components/Nav.jsx
frontend/src/containers/Listing.jsx
frontend/src/contexts/AuthContext.jsx

- my oopse
**Release Note:** Fixed incorrect variable access.

Fix: Fixed authContext

---

backend/helpers/utils.ts
backend/routes/collection.ts
backend/routes/recipe.ts
backend/tests/collection.test.ts
backend/tests/recipe.test.ts
frontend/src/api/routes.js
frontend/src/components/Nav.jsx
frontend/src/containers/Listing.jsx
frontend/src/containers/Recipe.jsx
frontend/src/contexts/AuthContext.jsx

MS-##: Remove auth on public endpoints
